spring:
  jmx.enabled: false
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  server:
    port: 8080
  application:
    name: ${service.name}
  datasource:
    url: ${sqlServerUrl}
    username: ${sqlServerUsername}
    password: ${sqlServerPassword}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: sql_server
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: true
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 500
          batch_versioned_data: true
  liquibase:
    enabled: false
  flyway:
    enabled: false


service:
  name: sql-migration-library

migration:
  schema-prefix: ${service.name} #optional, default empty string
  packages-to-scan: com.example* #optional, default = com.example*
  vendor: flyway #optional. default = liquibase
  flyway: #optional
    locations: classpath:db/migration/flyway #optional
    placeholders: #optional
      table_name: student
  liquibase: #optional. default = db/migration/liquibase/app-changelog.xml
    path-to-changelog: db/migration/liquibase/app-changelog.xml

